### ISSUE TITLE
Wabbajack-cli.exe Windows 11 File not found 'System.Runtime...'

### ISSUE THREAD

**Issue by thorsanvil** [wabbajack-tools/wiki#50]
Instructions I was following to verify the modlist (Vagabond)
https://github.com/Oghma-Infinium/Modding-Guides/blob/main/tutorials/Verifying%20your%20Modlist%20Install.md

Error message:

> C:\Wabbajack>"C:\Wabbajack\3.4.0.0\wabbajack-cli.exe" -h
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Wabbajack.CLI.Program.Main(String[])
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Wabbajack.CLI.Program.Main(String[])
   at Wabbajack.CLI.Program.<Main>(String[])

**Comment by EzioTheDeadPoet** [comment]
this is the issue list for the Wiki and not the app itself.
